### PR TITLE
Fix misc spelling

### PR DESCRIPTION
**Pull request by ottok**
Please provide feedback, give me time to finalize, and then merge the final version of this PR (so I get GitHub credits unlike happened in #25 and #26).

There are still a couple of things to tweak:

- Do you prefer "can't" or "can not" as a replacement for "cant"?
- Do you prefer "committish" or "commitish"?

```
± grep -rF commitish
debian/zsh/_gbp:		'--since=-[Start point for reading commits]:commitish:' \
debian/zsh/_gbp:		'--since=-[Start point for reading commits]:commitish:' \
gbp/git/repository.py:    def describe(self, commitish, pattern=None, longfmt=False, always=False,
gbp/git/repository.py:        @param commitish: the commit-ish to describe
gbp/git/repository.py:        @type commitish: C{str}
gbp/git/repository.py:        args.add(commitish)
gbp/git/repository.py:                                     (commitish, err.decode().strip()))
gbp/git/repository.py:    def get_commit_info(self, commitish):
gbp/git/repository.py:        @param commitish: the commit-ish to inspect
gbp/git/repository.py:        commit_sha1 = self.rev_parse("%s^0" % commitish)
gbp/git/repository.py:                                     % commitish)
gbp/git/repository.py:        return {'id': commitish,
gbp/scripts/import_ref.py:        # Use whatever is passed in as commitish
gbp/scripts/buildpackage_rpm.py:        info['commitish'] = repo.rev_parse('%s' % treeish)
gbp/scripts/buildpackage_rpm.py:        info['commitish'] = info['commit']
docs/manpages/gbp-dch.xml:	<arg><option>-s</option> <replaceable>commitish</replaceable></arg>
docs/manpages/gbp-dch.xml:        <arg><option>--since=</option><replaceable>commitish</replaceable></arg>
docs/po/gbp.pot:"<replaceable>commitish</replaceable></arg> "
docs/po/gbp.pot:"<arg><option>--since=</option><replaceable>commitish</replaceable></arg> "
docs/po/de.po:"option> <replaceable>commitish</replaceable></arg> <arg><option>--since=</"
docs/po/de.po:"option><replaceable>commitish</replaceable></arg> </group> <group> <group> "

± grep -rF committish
gbp/git/vfs.py:    def __init__(self, repo, committish=None):
gbp/git/vfs.py:        @param committish: the committish to act on
gbp/git/vfs.py:        self._committish = committish or 'HEAD'
gbp/git/vfs.py:                "%s:%s" % (self._committish, path)),
tests/component/deb/test_import_ref.py:    def test_from_committish(self, repo):
docs/manpages/gbp-dch.xml:        <term><option>--since=</option><replaceable>committish</replaceable>
docs/manpages/gbp-dch.xml:            <replaceable>committish</replaceable>.
docs/po/gbp.pot:msgid "<option>--since=</option><replaceable>committish</replaceable>"
docs/po/gbp.pot:"Start reading commit messages at <replaceable>committish</replaceable>.  "
docs/po/de.po:msgid "<option>--since=</option><replaceable>committish</replaceable>"
docs/po/de.po:"Start reading commit messages at <replaceable>committish</replaceable>.  "
```

### CODE REVIEW

**Comment by agx** [comment]
The corrections look good to me. Thanks for going through this.

> Do you prefer "can't" or "can not" as a replacement for "cant"?

`can't` please :smile: 

 > Do you prefer "committish" or "commitish"?

Git uses `<commit-ish>` so. `commitish` is preferred for code. `<commit-ish>` would be ideal for docs but `<commitish>` works as well. 

Regarding merging: I don't merge via github but rather fetch the diffs and apply them locally (preserving authorship)

**Comment by ottok** [comment]
> Regarding merging: I don't merge via github but rather fetch the diffs and apply them locally (preserving authorship)

GitHub will see the PR as being accepted if the git commit ID matches. If you rebase and change thus change the commit IDs, the PR will not show as accepted when you push to GitHub.

**Comment by agx** [comment]
> GitHub will see the PR as being accepted if the git commit ID matches.

I think I can manage to keep that the same. I usually tweak commit messages a bit so I don't need to nitpick too much so things change but I'll try to remember not to.

**Comment by ottok** [comment]
This is ready for final review now.

Commit follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention, and [CI passes](https://salsa.debian.org/otto/git-buildpackage/-/pipelines/622176) so nothing easily catchable has been broken.

**Comment by agx** [comment]
Besides the zsh bit this looks good. One request: could you switch this into three parts:

- `docs:` (changes to `docs`/, the changes to `HACKING` can go in there too
- `gbp:` (changes to `gbp/`, the changes in `tests/` and `examples/`) can go in there too)
- `debian:` Changes to `debian/`

Just that in case we spot a problem we don't have to revert all the bits (and we don't say `docs:` although we also change code).

**Comment by agx** [comment]
Thanks for splitting this up. The zsh bit is still broken, see comment above.

**Comment by ottok** [comment]
@agx Rebased on latest master - ready for final review.

**Comment by agx** [comment]
Applied, thanks!

**Pull request merged**
