### PR TITLE
setup gitattributes on clone

### PR DESCRIPTION
**Pull request by andrewshadura**
This is a work-in-progress implementation which would fix the Debian bug: [#973755](https://bugs.debian.org/973755).

Please see more about the motivation in the bug itself, [dgit(7)](https://manpages.debian.org/buster/dgit/dgit.7.en.html#GITATTRIBUTES), [git-deborig(1)](https://manpages.debian.org/buster/devscripts/git-deborig.1.en.html) and in the commit messages of the individual commits.

I posted this WIP PR to get comments on the general direction of work. I will be adding tests if you approve the approach I’ve taken.

### CODE REVIEW

**Comment by andrewshadura** [comment]
So, I guess, the open discussion points are:
 * `os.path` vs `pathlib`
 * bikeshedding the names of options, arguments, subcommands…
 * typing
 * f-strings (and Python 3.6+) vs %-formatting
 * for all of the above: gradual change (new code uses new features) vs consistency across the codebase

**Comment by agx** [comment]
thanks for the patches!

> *  os.path vs pathlib

We didn't use it so far (although it's there since 3.4) so i'd stick with `os.path` for the moment

>    bikeshedding the names of options, arguments, subcommands…

Those look fine, i was on the fence if we really need a new subcommand, but why not. Things left in this case are

- manpage
- update list of commands in `debian/control`
- a component test testing round trip with odd attributes would be great

> *  typing

as in type hints? No objections but also no requirement

>   f-strings (and Python 3.6+) vs %-formatting

There's no strict rules regarding features from newer python versions (except that backporting to Debian stable should stay manageable) so f-strings are are fine (i never was a fan of `.format()` but we have some of these in the codebase too).

> for all of the above: gradual change (new code uses new features) vs consistency across the codebase

i'd go for gradual change here but won't mind patches cleaning out e.g. `.format()` so we have two string formats (`f` and `%` not three).

**Comment by agx** [comment]
dpkg-mergechangelog is another contender for automatic git attribute setup. Should we make 

`gbp setup-gitattribues` 

and then have

`gbp setup-gitattribues [--dgit-defuse-attrs] [--dpkg-mergechangelog] [--all]` 

defaultint to

`gbp setup-gitattribues --all` 

(the `dpkg-mergechangelogs` part isn't required for this MR but we should phrase the manpage in a way that says that `--all` is the default and that more attributes might be added). I'm not sure if `--all` is the best default though longterm.

**Comment by andrewshadura** [comment]
> but we should phrase the manpage in a way that says that `--all` is the default and that more attributes might be added).

Did you have something like 2738786 in mind?

**Comment by agx** [comment]
> > but we should phrase the manpage in a way that says that `--all` is the default and that more attributes might be added).
> 
> Did you have something like [2738786](https://github.com/agx/git-buildpackage/commit/2738786347102a40a6bc2be19f396e7baa462c38) in mind?

yes!

**Comment by andrewshadura** [comment]
One thing left: the new functions in `gbp/scripts/common/repo_setup.py` still use pathlib; I tried to rewrite them to `os.path` but I feel they’ve become less readable.

I still have that code stashed if you’d rather have me complete that part of work, or maybe some pathlib won’t harm :slightly_smiling_face:

**Comment by andrewshadura** [comment]
I wasn’t sure where to add tests for defuse-on-clone; I added them in the same file as the rest, but if you’d prefer them in the file for clone, please let me know.

**Comment by agx** [comment]
> I still have that code stashed if you’d rather have me complete that part of work, or maybe some pathlib won’t harm slightly_smiling_face

`os.path` should look o.k. but let's try `pathlib` here.

**Comment by agx** [comment]
> I wasn’t sure where to add tests for defuse-on-clone; I added them in the same file as the rest, but if you’d prefer them in the file for clone, please let me know.

we group component tests by script so i think it's better to move the clone parts to `clone`.

**Comment by andrewshadura** [comment]
> `os.path` should look o.k. but let's try `pathlib` here.

Great, thanks :slightly_smiling_face:

> we group component tests by script so i think it's better to move the clone parts to `clone`.

Done!

**Comment by andrewshadura** [comment]
I was also thinking about making `import-orig` always import files as they are, without using Git attributes, but my initial attempt at this opened a can of worms.

I thought it’d be great to manually stage files instead of using `git add` which can’t ignore attributes. Turned out, I need to `stat` files before adding them (because executable bit), and `os.walk` throws the stat data away. I could recursively scan myself using `os.scandir` (and liw even generously offered [his implementation](http://git.liw.fi/obnam/tree/obnamlib/vfs.py#n260) under CC0), but then I realised I’d need to use `git update-index --index-info`, which is probably a bit tricky, and it would still probably be slower than `git add` because hashing objects is a fork/exec each time (unless I resort to reimplementing that part as well in pure Python).

So I decided to just unconditionally defuse attributes when importing for now. And also I’m writing a patch for Git to add `--no-filters` to `git add`.

I will likely submit this work as a separate pull request after this one is merged.

**Comment by agx** [comment]
Looks good to me, i'll try to get this another test drive over the week and when nothing crops up merge. Thanks!

**Comment by agx** [comment]
`make` throws out these flake8 errors on Debian bullseye

```flake8 
./gbp/scripts/setup_gitattributes.py:41:5: E303 too many blank lines (2)
./gbp/scripts/common/repo_setup.py:38:1: E302 expected 2 blank lines, found 1
./gbp/scripts/common/repo_setup.py:50:1: E305 expected 2 blank lines after class or function definition, found 1
./gbp/scripts/common/repo_setup.py:50:65: E703 statement ends with a semicolon
./gbp/scripts/common/repo_setup.py:51:80: E703 statement ends with a semicolon
./gbp/scripts/common/repo_setup.py:58:1: E302 expected 2 blank lines, found 1
./gbp/scripts/common/repo_setup.py:82:1: E302 expected 2 blank lines, found 1
./tests/component/deb/test_setup_gitattributes.py:72:25: E128 continuation line under-indented for visual indent
./tests/component/deb/test_setup_gitattributes.py:79:25: E128 continuation line under-indented for visual indent
./tests/component/deb/test_setup_gitattributes.py:85:5: E303 too many blank lines (2)
./tests/component/deb/test_setup_gitattributes.py:99:25: E128 continuation line under-indented for visual indent
./tests/component/deb/test_setup_gitattributes.py:111:5: E303 too many blank lines (2)
./tests/component/deb/test_setup_gitattributes.py:125:25: E128 continuation line under-indented for visual indent
./tests/component/deb/test_setup_gitattributes.py:147:5: E303 too many blank lines (2)
./tests/component/deb/test_setup_gitattributes.py:161:25: E128 continuation line under-indented for visual indent
./tests/component/deb/test_setup_gitattributes.py:181:1: W391 blank line at end of file
./tests/component/deb/test_clone.py:99:25: E128 continuation line under-indented for visual indent
```

**Comment by andrewshadura** [comment]
> `make` throws out these flake8 errors on Debian bullseye

Thanks, fixed.

**Comment by andrewshadura** [comment]
By the way, are there any hopes of having this in Bullseye? (I hope it’s not too late) :slightly_smiling_face:

**Comment by agx** [comment]
i still have  failing test here on bullseye:

```
======================================================================
FAIL: Doctest: tests.doctests.test_GitRepository.test_make_tree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for test_make_tree
  File "/var/scratch/src/git-buildpackage/git-buildpackage/tests/doctests/test_GitRepository.py", line 931, in test_make_tree

----------------------------------------------------------------------
File "/var/scratch/src/git-buildpackage/git-buildpackage/tests/doctests/test_GitRepository.py", line 954, in test_make_tree
Failed example:
    list(repo.list_tree(newtree, recurse=False, paths='testfile', sizes=True))
Expected:
    [['100644', 'blob', '19af7398c894bc5e86e17259317e4db519e9241f', 20, b'testfile']]
Got:
    [['100644', 'blob', '19af7398c894bc5e86e17259317e4db519e9241f', '20', b'testfile']]
```

(and having the size as int would indeed be good)

**Comment by andrewshadura** [comment]
It looks like I’ve forgotten some change…

**Comment by agx** [comment]
merged now, thanks!

**Pull request closed without merging**
