### PR TITLE
add build-deb script

### PR DESCRIPTION
**Pull request by rubicks**
Here's a script that builds and packages `git-buildpackage` with the regular debian build tools within a docker container. This is useful for creating the package on a system that does not (yet) have a `git-buildpackage` installation.

### CODE REVIEW

**Comment by agx** [comment]
Having something like this is useful but I'd rather not have two similar docker files in one project. If we want to add that 

tests/helpers/run-in-docker

should move to packagig/ and get the necessary parts added so it can also build a git-buildpackage deb triggered by a command line option. This would make sure we exercise large parts of the script on every build to prevernt bitrot.

**Comment by rubicks** [comment]
@agx I understand your concerns regarding similar `Dockerfile`s, but this patch doesn't actually use any --- unless you count the inlined heredoc.

If you want, I can amend my patch to move `tests/helpers/run-in-docker` to `packaging/run-in-docker` and add some simple `getopts` parsing.

**Comment by rubicks** [comment]
@agx travis is failing because `flake8` doesn't like the formatting in a file I didn't touch.

**Comment by rubicks** [comment]
@agx thanks for fixing the `flake8` problems; travis looks good. I've squashed and rebased a couple times to clean up the patch. By default, `run-in-docker` will `make all+net`, but it can be directed to build debian package artifacts with various options.

**Comment by agx** [comment]
Pushed. Thanks.

**Comment by rubicks** [comment]
@agx welcome!

**Pull request closed without merging**
