### PR TITLE
gbp import-orig: Allow to import the requested version with --uscan

### PR DESCRIPTION
**Pull request by sathieu**
Closes: [#741148](https://bugs.debian.org/741148)

### CODE REVIEW

**Comment by sathieu** [comment]
I've updated the PR to use `--download-debversion` instead of `--download-version`, which makes more sense.

**Comment by agx** [comment]
Looks good at a quick glance. The manpage would need an update too. 

Did you check why the tests fail?

**Comment by sathieu** [comment]
I've pushed again with manpage additions. And CI now passes...

**Comment by agx** [comment]
Applied. Thanks!

**Pull request closed without merging**
