### PR TITLE
Implement 'run-in-docker -c podman'

### PR DESCRIPTION
**Pull request by ottok**
> *NOTE*: This is work-in-progress, do not merge. Posting for visibility and comments.

Typically developers have either Docker or Podman on their laptops for running containers. As Podman follows nearly identical syntax as Docker, add new option '-c' that allows to specify Podman or Docker as the container command, with Docker being default if nothing is defined for the sake of backwards compatibility.

### CODE REVIEW

**Comment by ottok** [comment]
CI in https://salsa.debian.org/otto/git-buildpackage/-/jobs/5147508 fails on seemingly unrelated issue which I am unable to reproduce locally with `run-in-docker package`:

```
dh_installdocs: error: Cannot find (any matches for) "NEWS" (tried in ., debian/tmp)
```

**Comment by agx** [comment]
Looks as if the salsa repo you linked to is private, i get a 404

**Comment by agx** [comment]
> dh_installdocs: error: Cannot find (any matches for) "NEWS" (tried in ., debian/tmp)

should be fixed now. Interesting that it didn't fail over here.

**Comment by ottok** [comment]
CI passing at https://salsa.debian.org/otto/git-buildpackage/-/pipelines/625116 (but irrelevant, since it does not run this command).

Anyway used this for a day and it is ready for review.

**Comment by agx** [comment]
Thanks (and as I'm using podman myself this is welcome). One itch: instead of multiple `${container_cmd:-docker}` why not sec `container_cmd="docker"` once and use it everywhere?

**Comment by agx** [comment]
Merged now, thanks!

**Pull request merged**
