### PR TITLE
Feature/fixes

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by agx** [comment]
Hi,
Thanks for the patches!

On Fri, Dec 15, 2017 at 02:34:14PM -0800, Markus Lehtonen wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/agx/git-buildpackage/pull/36
> 
> -- Commit Summary --
> 
>   * rpm packaging: update dependency on rpm-build

Cherry-picked, thanks.

>   * GitRepository.make_tree: Python compatibility fix

Can you enable Python3.4 in travis then as well and see that the test
pass? Otherwise fixing just one place is bound to fail.

>   * create_remote_repo: fix typo

Cherry-picked as well. Thanks!
 -- Guido

**Comment by marquiz** [comment]
> Can you enable Python3.4 in travis then as well and see that the test
> pass? Otherwise fixing just one place is bound to fail.

Yeah, that's right. There are other similar fixes needed, too.

**Comment by marquiz** [comment]
Now the tests pass, at least :)

**Comment by agx** [comment]
I'm not sure it's worth supporting Python3 < 3.5 though. String/Bytes handling was just too broken in these releases that I'd rather not clutter the codebase with it.

**Comment by marquiz** [comment]
> I'm not sure it's worth supporting Python3 < 3.5 though. String/Bytes handling was just too broken in these releases that I'd rather not clutter the codebase with it.

I understand this, and the bytestring formatting is cumbersome and ugly :/ However, this is still a problem for many distros. For example, I'm using the latest openSUSE which has Python 3.4. There are very few places that would need this workaround. Would you consider a wrapper class or function that could then be removed/reverted after all major distros have Python 3.5?

**Comment by agx** [comment]
Yes, if we have something that resembles the 3.5+ behaviour and that's fine. I would be surpised if nobody has done this already but I didn't come across it yet.

**Comment by marquiz** [comment]
> Yes, if we have something that resembles the 3.5+ behaviour and that's fine. I would be surpised if nobody has done this already but I didn't come across it yet.

I didn't find anything on a quick search, but, wrote a simple wrapper function similar to the format_str() we already have.

**Comment by agx** [comment]
Pushed. Thanks!

**Pull request closed without merging**
