### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by agx** [comment]
Pushed. Thanks.

**Comment by ottok** [comment]
This was merged as f28a26b4e7b279056f73f8171e83ea6f776860f8 and af16f59214306b56ffc79e4c5c5a206561f9c3ff which are exactly the same as in this PR but somehow this PR is marked as 'closed' and I didn't get any git credits for my contribution, which I should have gotten.

**Comment by agx** [comment]
I don't see a problem: The commits are attributed to you as they should be : 

- https://git.sigxcpu.org/cgit/git-buildpackage/commit/?id=f28a26b
- https://git.sigxcpu.org/cgit/git-buildpackage/commit/?id=af16f59

image

**Comment by ottok** [comment]
Sorry, I meant GitHub credits, not just git credits. GitHub shows on the profile page special boxes and accomplishments if PRs are merged.

**Comment by agx** [comment]
I'm not using github's merge feature and merge locally. Basically the only reason MRs are open is because it couldn't be disabled back then when I started to mirror here :smile:

**Pull request closed without merging**
