### PR TITLE
Feature/gbp pull

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by agx** [comment]
Other branches should be ff otherwise something is wrong. The second part makes sense but needs a test.

**Comment by marquiz** [comment]
> Other branches should be ff otherwise something is wrong.

OK, makes sense.


> The second part makes sense but needs a test.

Good, point. There were not component unit tests back in the days I originally wrote this :)

**Comment by marquiz** [comment]
I now added unit test for the --all option.

I didn't include the other commit for now. But, I still think there is something broken in the gbp-pull logic when --force is used. The currently checked-out branch is merged but the others are just reset which I see kind of bad because the end result depends on the currently checked out branch. For example, if I happened to be on pq branch the debian branch would be simply reseted to whatever the upstream has. But, if I happened to be on the debian branch it would be merged, instead. Any thoughts?

**Comment by marquiz** [comment]
I see you pulled the patches. Thanks!

However, any comments on the --force logic question I raised?

**Comment by agx** [comment]
@marquiz could open another PR with you proposed change regarding merge vs. reset? The code in this PR is merged.

**Pull request closed without merging**
